name: Build PPSSPP for iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        brew update
        brew install ldid cmake make gnu-sed

    - name: Clone PPSSPP source
      run: |
        git clone https://github.com/hrydgard/ppsspp.git
        cd ppsspp
        git submodule update --init --recursive

    - name: Build application and packages
      run: |
        make -C ppsspp git-version.cpp
        make all

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PPSSPP-Build
        path: |
          PPSSPP_*.ipa
          org.ppsspp.ppsspp-dev-latest_*.deb
