name: Build PPSSPP iOS (Fixed Paths)

on:
  workflow_dispatch:
  push:
    branches: [master]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Temporary tag for git describe
        run: git tag v0.0.0

      - name: Install required tools
        run: |
          brew install cmake ninja make gnu-sed ldid
          which make
          which gsed
          which ldid

      - name: Setup fake signing keychain
        run: |
          security create-keychain -p "password" build.keychain
          security import certificate.p12 -k build.keychain -P "password" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security unlock-keychain -p "password" build.keychain
          security set-keychain-settings -lut 21600 build.keychain

      - name: Build (Makefile)
        run: make all

      - name: Upload IPA and DEB
        uses: actions/upload-artifact@v4
        with:
          name: ppsspp-ios-build
          path: |
            *.ipa
            *.deb
