name: Generate iOS IPA

on:
  workflow_dispatch:
    inputs:
      buildVariant:
        type: choice
        description: 'Build Variant'
        required: true
        default: 'release'
        options:
          - release
          - debug

jobs:
  build-ipa:
    name: Build ${{ github.event.inputs.buildVariant }} IPA
    runs-on: macos-14  # Use the latest macOS runner

    env:
      BUILD_DIR: ${{ github.workspace }}/ppsspp/build-ios

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install ldid gnu-sed make cmake || true
          echo "/usr/local/opt/gnu-sed/libexec/gnubin" >> $GITHUB_PATH
          echo "/usr/local/opt/make/libexec/gnubin" >> $GITHUB_PATH

      - name: Prepare code signing files
        run: |
          cp "${{ github.workspace }}/certificate.p12" certificate.p12
          cp "${{ github.workspace }}/ent.xml" ent.xml

      - name: Ensure valid version tags
        id: valid-tags
        run: |
          TAG_COUNT=$(git tag -l 'v[0-9]*' | wc -l | tr -d ' ')
          echo "count=$TAG_COUNT" >> $GITHUB_OUTPUT

      - name: Fetch upstream tags if needed
        if: steps.valid-tags.outputs.count == '0'
        run: |
          git remote add upstream https://github.com/hrydgard/ppsspp.git
          git fetch --tags upstream

      - name: Set GIT_VERSION variable
        run: |
          echo "GIT_VERSION=$(git describe --tags --always)" >> $GITHUB_ENV

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@main
        with:
          key: ios
          create-symlink: true

      - name: Configure and build (CMake + Make)
        env:
          CC: clang
          CXX: clang++
          USE_CCACHE: 1
        run: |
          set -e
          cd ppsspp
          mkdir -p build-ios
          echo "const char *PPSSPP_GIT_VERSION = \"${GIT_VERSION}\";" > git-version.cpp
          echo "#define PPSSPP_GIT_VERSION_NO_UPDATE 1" >> git-version.cpp
          cd build-ios
          cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchains/ios.cmake -DCMAKE_BUILD_TYPE=${{ github.event.inputs.buildVariant }} ..
          make -j$(sysctl -n hw.ncpu)
          echo "${GIT_VERSION#v}" > PPSSPP.app/Version.txt

      - name: Code sign framework and app
        run: |
          cd $BUILD_DIR
          if [ -f PPSSPP.app/Frameworks/libMoltenVK.dylib ]; then
            ldid -S ../../ent.xml -K ../../certificate.p12 PPSSPP.app/Frameworks/libMoltenVK.dylib
          fi
          ldid -S ../../ent.xml -K ../../certificate.p12 PPSSPP.app

      - name: Package IPA
        id: package
        run: |
          cd $BUILD_DIR
          mkdir -p Payload
          cp -r PPSSPP.app Payload/
          IPA_NAME="PPSSPP_${GIT_VERSION#v}_${{ github.event.inputs.buildVariant }}.ipa"
          zip -r9 "$IPA_NAME" Payload
          mv "$IPA_NAME" "${{ github.workspace }}/"
          echo "ipa_name=$IPA_NAME" >> $GITHUB_OUTPUT

      - name: Upload IPA artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.ipa_name }}
          path: ${{ github.workspace }}/${{ steps.package.outputs.ipa_name }}
