name: Build PPSSPP iOS IPA and Upload to Release Draft

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.2.2
      with:
        submodules: recursive

    - name: Install Dependencies
      run: brew install cmake

    - name: Build IPA
      run: make ipa

    - name: Determine Version
      id: version
      run: |
        VERSION=$(date +'%Y.%m.%d')
        echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
        IPA_NAME="PPSSPP-$VERSION.ipa"
        mv PPSSPP.ipa "$IPA_NAME"
        echo "IPA_NAME=$IPA_NAME" >> $GITHUB_OUTPUT

    - name: Create Release Draft
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version.outputs.VERSION }}
        release_name: "PPSSPP iOS Build ${{ steps.version.outputs.VERSION }}"
        body: |
          Daily PPSSPP iOS build for version ${{ steps.version.outputs.VERSION }}.
        draft: true
        prerelease: true

    - name: Upload IPA Asset to Release
      uses: actions/upload-release-asset@v1.1.3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ${{ steps.version.outputs.IPA_NAME }}
        asset_name: ${{ steps.version.outputs.IPA_NAME }}
        asset_content_type: application/octet-stream
