name: Build PPSSPP on macos-latest

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Type of build (Release, Debug)'
        required: false
        default: 'Release'
        type: string

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Verify ppsspp directory exists
        run: |
          if [ ! -d "ppsspp" ]; then
            echo "Error: 'ppsspp' directory not found."
            exit 1
          fi

      - name: Install dependencies
        run: brew install cmake make ldid

      - name: Add GNU make to PATH
        run: echo "$(brew --prefix make)/libexec/gnubin" >> $GITHUB_PATH

      - name: Build PPSSPP
        run: |
          cd ppsspp
          echo "const char *PPSSPP_GIT_VERSION = \"$(git describe --always)\";" > git-version.cpp
          echo "#define PPSSPP_GIT_VERSION_NO_UPDATE 1" >> git-version.cpp

          mkdir -p build-ios
          cd build-ios

          cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchains/ios.cmake -DCMAKE_BUILD_TYPE=${{ inputs.build_type }} ..
          /usr/local/opt/make/libexec/gnubin/make -j$(sysctl -n hw.ncpu)

          ln -s ./ Payload
          git describe --tags --match="v*" | /usr/local/opt/gnu-sed/libexec/gnubin/sed -e 's@-\\([^-]*\\)-\\([^-]*\\)$@-\\1-\\2@;s@^v@@;s@%@~@g' > PPSSPP
