name: Build PPSSPP for iOS (Better Compatibility)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-11  # macOS 11 (Big Sur) supports Xcode 9.4.1
    timeout-minutes: 120  # Build may take longer with older tools

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Xcode 9.4.1
      run: |
        # Download and install Xcode 9.4.1
        curl -o xcode.xip https://download.developer.apple.com/Developer_Tools/Xcode_9.4.1/Xcode_9.4.1.xip
        xip -x xcode.xip
        sudo mv Xcode.app /Applications/Xcode_9.4.1.app
        
        # Accept license and set as default
        sudo xcode-select -s /Applications/Xcode_9.4.1.app/Contents/Developer
        sudo xcodebuild -license accept
        
        # Install required SDKs
        /Applications/Xcode_9.4.1.app/Contents/Developer/usr/bin/xcodebuild -downloadPlatform iOS

    - name: Install dependencies
      run: |
        brew update
        brew install ldid cmake make gnu-sed
        brew install libpng

    - name: Clone PPSSPP source
      run: |
        git clone https://github.com/hrydgard/ppsspp.git
        cd ppsspp
        git submodule update --init --recursive
        git checkout tags/v1.17.1  # Use a compatible version

    - name: Build application and packages
      run: |
        # Set environment variables for iOS 11 SDK
        export SDKROOT=/Applications/Xcode_9.4.1.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS11.4.sdk
        export IPHONEOS_DEPLOYMENT_TARGET=11.4
        export DEVELOPER_DIR=/Applications/Xcode_9.4.1.app/Contents/Developer
        
        # Build with older tools
        make all LDID="ldid" MAKE="make" SED="gsed"

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: PPSSPP-Build
        path: |
          PPSSPP_*.ipa
          org.ppsspp.ppsspp-dev-latest_*.deb
