name: Build and Sign PPSSPP for iOS (iOS 17.5 Compatible)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_DIR: ${{ github.workspace }}/ppsspp/build-ios
  CERTIFICATE_PASSWORD: password
  KEYCHAIN_PASSWORD: password

jobs:
  build:
    runs-on: macos-14-arm64

    steps:
      - name: Checkout This Repo
        uses: actions/checkout@v4

      - name: Clone PPSSPP Source
        run: |
          git clone --recursive https://github.com/hrydgard/ppsspp.git ppsspp

      - name: Install Dependencies
        run: |
          brew install cmake gnu-sed make

      - name: Set Deployment Target & Configure CMake
        run: |
          mkdir -p $BUILD_DIR
          cd $BUILD_DIR
          export IPHONEOS_DEPLOYMENT_TARGET=12.0
          cmake .. -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchains/ios.cmake -G Xcode -DIPHONEOS_DEPLOYMENT_TARGET=12.0

      - name: Build Project
        run: |
          cd $BUILD_DIR
          cmake --build . --config Release

      - name: Import Code Signing Certificate
        run: |
          security create-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security import ../../certificate.p12 -k build.keychain -P "$CERTIFICATE_PASSWORD" -T /usr/bin/codesign
          security list-keychains -s build.keychain
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" build.keychain
          security set-keychain-settings -lut 21600 build.keychain
          security set-key-partition-list -S apple-tool:,apple: -s -k "$KEYCHAIN_PASSWORD" build.keychain

      - name: Sign the App Bundle
        run: |
          cd $BUILD_DIR
          if [ -f "PPSSPP.app" ]; then
            echo "Signing PPSSPP.app..."
            codesign -s "iPhone Developer" --entitlements ../../ent.xml --force --deep PPSSPP.app
          else
            echo "::error::PPSSPP.app not found"
            exit 1
          fi

      - name: Package IPA
        run: |
          cd $BUILD_DIR
          mkdir -p Payload
          cp -r PPSSPP.app Payload/
          zip -qry PPSSPP-iOS.ipa Payload
          echo "✅ IPA created at $BUILD_DIR/PPSSPP-iOS.ipa"

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PPSSPP-iOS
          path: ${{ env.BUILD_DIR }}/PPSSPP-iOS.ipa
