name: Build iOS PPSSPP IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    env:
      BUILD_DIR: ppsspp/build-ios
      IPHONEOS_DEPLOYMENT_TARGET: "12.0"

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install dependencies
        run: |
          brew install cmake ninja

      - name: Clone MoltenVK
        run: |
          git clone https://github.com/KhronosGroup/MoltenVK.git deps/MoltenVK
          cd deps/MoltenVK && ./fetchDependencies --ios && cd ../..

      - name: Copy MoltenVK frameworks
        run: |
          mkdir -p ppsspp/ios/MoltenVK
          cp -R deps/MoltenVK/Package/Latest/MoltenVK/iOS/MoltenVK.framework ppsspp/ios/MoltenVK/
          cp deps/MoltenVK/Package/Latest/MoltenVK/iOS/libMoltenVK.dylib ppsspp/ios/MoltenVK/

      - name: Configure via CMake
        run: |
          mkdir -p $BUILD_DIR
          cd $BUILD_DIR
          cmake ../.. \
            -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchains/ios.cmake \
            -DIOS_PLATFORM=OS \
            -G Xcode \
            -DCMAKE_XCODE_ATTRIBUTE_IPHONEOS_DEPLOYMENT_TARGET=$IPHONEOS_DEPLOYMENT_TARGET

      - name: Set up signing (.p12 & provisioning)
        run: |
          CERT_P12="certs/signing.p12"
          PROV_PROFILE="certs/ppsspp.mobileprovision"
          KEYCHAIN_PW="password"
          security create-keychain -p "$KEYCHAIN_PW" build.keychain
          security import "$CERT_P12" -k build.keychain -P "password" -T /usr/bin/codesign
          security set-keychain-settings -lut 21600 build.keychain
          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
          cp "$PROV_PROFILE" ~/Library/MobileDevice/Provisioning\ Profiles/

      - name: Build & sign PPSSPP
        run: |
          cd $BUILD_DIR
          xcodebuild \
            -scheme PPSSPP \
            -configuration Release \
            -destination generic/platform=iOS \
            CODE_SIGN_STYLE=Manual \
            CODE_SIGN_IDENTITY="iPhone Developer" \
            PROVISIONING_PROFILE_SPECIFIER="PPSSPP Profile" \
            IPHONEOS_DEPLOYMENT_TARGET=$IPHONEOS_DEPLOYMENT_TARGET \
            clean build

      - name: Package IPA
        run: |
          cd $BUILD_DIR
          mkdir -p Payload
          cp -R Release-iphoneos/PPSSPP.app Payload/
          zip -qry PPSSPP-iOS.ipa Payload/

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: PPSSPP-iOS
          path: $BUILD_DIR/PPSSPP-iOS.ipa
